# Generated by Django 5.0.1 on 2024-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_analysis_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('success', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('class_id', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('request_timestamp', models.DateTimeField(verbose_name='date published')),
                ('response_timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
